// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/calc-home/CommandFirst.tsx": () => import("../components/mockups/calc-home/CommandFirst.tsx"),
  "./components/mockups/calc-home/DenseDirectory.tsx": () => import("../components/mockups/calc-home/DenseDirectory.tsx"),
  "./components/mockups/calc-home/ScenarioNav.tsx": () => import("../components/mockups/calc-home/ScenarioNav.tsx")
};
